url: http://127.0.0.0.1:4000
baseurl: 

# Site settings
title: Atkere Anantha Srinivas Pai & Sons
email: info@aaspai.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Atkere Ramachandra Pai 
  pic: 1
  position: Managing Partner
  social:
    - title: twitter
      url: #
    - title: facebook
      url: https://www.facebook.com/atkereramachandra.pai?fref=nf
      

- name: Atkere Anantha Srinivas Pai	
  pic: 2
  position: Founding Partner 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: https://www.facebook.com/
      

- name: Atkere Vishwanath Pai
  pic: 3
  position: Managing Partner
  social:
    - title: twitter
      url: #
    - title: facebook
      url: https://www.facebook.com/vishwanath.pai.378
      

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Mahamaya,  Main Road
  - line: Koteshwar, KAR 576222

# Build settings
markdown: kramdown
permalink: pretty
